### ISSUE TITLE
Week 2: User input

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#10]
Modify code to ask user input and query accordingly. This should work in a loop to repeatedly allow querying, and empty string should exit the loop

**Comment by tiigit** [comment]
This task is now resolved, I think. Will you review my code @rrimpila @ciccmin ? :)

**Comment by ciccmin** [comment]
The code works well on my end!

I'm thinking: when inputing a query with operators on lowercase, the program crashes and gives a syntax error. Should we add a `try / except SyntaxError` feature in case the user inputs a query with operators in lowercase? It could be an error message saying the input was wrong, and reminding the user to check that the operators are capitalised

**Comment by tiigit** [comment]
Yes! Good notice, I will fix that :)

**Comment by tiigit** [comment]
I fixed the lowercase letter operator issue, but came up with a new one. I tried to find out what happens if the user search query doesn't have any matching documents, so I tried to find the words "cool" and "awesome" 😆 What happens is this:
![image](https://user-images.githubusercontent.com/116378573/215073839-1bd02cf2-5d0f-4a35-bbfa-982bd7fd171b.png)
How do we want to handle these cases @rrimpila @ciccmin ? Is it okay if I just fix it in a way that it won't show the matrix, but instead prints out a message saying no results were found?

**Comment by ciccmin** [comment]
Whoops! Yep, that must be caused by my attempt at fixing issue #11. I'll patch it up as soon as I get to my computer

**Comment by ciccmin** [comment]
Hello! I fixed the issue (turns out that there were matches for "cool" but not for "awesome", so the zero matrix the program presented was technically right, but now the program gives out a verbal answer stating that there were no matches found, like in any other instances where there are no matches.
I think I tested all possibilities, but in case further issues with this arise, hmu and I'll try to fix my mistakes :D

**Comment by rrimpila** [comment]
I agree, it looks like it is working well. I believe we can close this, and continue with corrections to unknown terms if needed.
