### ISSUE TITLE
Week 2: Error handling on unknown terms

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#11]
Prevent program from crashing if the query terms are not present. Maybe return some error message on the term not found...

**Comment by ciccmin** [comment]
Hello, @rrimpila @tiigit ! I came up with a potential solution to this issue. Could you please review it? I tried explaining as much as I can in the in-code comments

**Comment by tiigit** [comment]
@ciccmin I took a look at your code and I think the idea for handling those errors was good! The part that should handle the situation when there are no matches at all doesn't seem to work though. I actually posted a message about this to issue #10 before I noticed this message from you, check that one out :D

**Comment by ciccmin** [comment]
Hello! I cleaned up the code and fixed an issue I had accidentally caused, which was mentioned in issue #10.
Could anyone review the code now, @tiigit, @rrimpila? If further issues with this arise, hmu and I'll try to fix them :D

**Comment by rrimpila** [comment]
It looks very beautiful, I ran into a minor issue with search "kissa AND koira" where the No matches message contained both and I believe it is due to the regex not splitting on &. I added a comment on the row in the commit, I am not sure where you'll find it, but I believe it pings you since I tagged it. If you agree with my suggestion there, I think it's ok to then close this issue.

**Comment by ciccmin** [comment]
Great! I agree with your suggestion and will close the issue after I push the changes :D

**Comment by tiigit** [comment]
Hey! The code looks good. I just need to check if I understood correctly; if I search for "word1 AND word2" the search engine should only prints the documents that contains BOTH of those words?
Right now our code works so that if I search for "unknownword" it returns no documents (which is correct and the way it should be), but when I search for "unknownword AND this" the search engine returns the documents in which "this" occurs. But it shouldn't be like that, right? Because there should be no documents that match both of those words since there are no documents matching "unknownword". Only if I search for "unknownword OR this" should the matching documents for this appear.

Would either one of you @ciccmin @rrimpila like to tackle on this error still? 🥲 
I'm currently trying to figure out a way to resolve issue #14 and will probably still continue with that tomorrow!

**Comment by ciccmin** [comment]
Hello! I think I was able to fix it without further bugs showing up, but I'll let you guys review it first before closing the issue :D

**Comment by tiigit** [comment]
I think it works now! Good job :)

**Comment by rrimpila** [comment]
I realized that this error handling cannot support more complicated queries. For example "cat AND ( dog OR koira )" should obviously return something, since "cat AND dog" finds documents. But the "koira" throws keyError, and trying to split the query to accommodate arbitrarily complicated queries will not be feasible. 
I think we need to check for the key existing already in `rewrite_token` to make it work (ie, key not existing equals a matrix of no hits). I can take a look if I get this working.

**Comment by rrimpila** [comment]
I think I got it, this version checks for the key within rewrite_token, and queries the matrix for hits if the key exists and otherwise returns an empty row that can then be used in the operations. Now the keyError isn't thrown, so I removed the try - catch. 
Could you review?

**Comment by tiigit** [comment]
Nice, this looks really good and I at least don't get any errors, good job! 😃  If @ciccmin approves, we can agree to be completely ready with the task for this week?

**Comment by ciccmin** [comment]
It works perfectly now! Great :D And I approve as well yes!
