### ISSUE TITLE
Data scraping: read and parse document

### ISSUE THREAD

**Issue by tiigit** [rrimpila/tiramisu#46]
Read the document made as a result of the scraping and parse it in a way that can be used by the software.
This issue needs to be handled after #45

**Comment by rrimpila** [comment]
Due to query limiting I had to split the scraping into multiple parts and so the files are also yearly separated.
```
	data/fanfics2018.json
	data/fanfics2019.json
	data/fanfics2020.json
	data/fanfics2021.json
	data/fanfics2022.json
```
These should be readable as the previous data was, and when you parse them with json parser
```
import json
...
documents = json.loads(content)
```
You should get arrays containing dictionaries of "works" `{'categories': ...,'characters':...,'fandoms':...,'rating':...,'relationships':...,'tags':...,'title':...,'warnings':...,'id':...,'date_published':...,'content'...} `. The arrays need to be joined to be passed forward.

The content has p and h3 tags, which the previous document content did not. I don't expect this to cause any issues, but if they do, let me know and I'll see if we can bypass them easily

**Comment by tiigit** [comment]
This current version uses only the fanfics2018.json data.

Spacy highlighting apparently doesn't work for too long articles so, for now, I limited the spacy function so that it only works if the article text is less that 100 000 characters.

**Comment by tiigit** [comment]
Seems like the program (or at least my computer) cannot process all of the json-files at the same time. Reading and parsing works for all of the files when tested in the command line (by exiting program after the initial processing and the making of the variables "documents", "documents_titles", etc.), but the program kills itself when I try to run it on the web ui.

We'll have to think about cutting the dataset to smaller amount of fanworks.
