### ISSUE TITLE
Week 2: Create project base

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#9]
Copy and paste relevant code from demo

**Comment by ciccmin** [comment]
I encountered an error "ModuleNotFoundError: No module named 'sklearn'", despite having installed sklearn with pip3. 

The issue was resolved by installing sklearned by using its longer name, so with the command "pip3 install scikit-learn".

More info in the link below.

https://towardsdatascience.com/fix-modulenotfounderror-sklearn-99db60ed5d

**Comment by tiigit** [comment]
Thanks @ciccmin , this command worked for me!
Ps. This part of the task is apparently now done so I'll close the issue :)
